# Generated by Django 4.2 on 2023-04-29 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='countries',
        ),
    ]
