# Generated by Django 4.2 on 2023-04-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='phonecode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='shortname',
            field=models.CharField(default='', max_length=3),
        ),
    ]
