# Generated by Django 4.2 on 2023-04-29 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_country_phonecode_country_shortname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='phonecode',
        ),
        migrations.RemoveField(
            model_name='country',
            name='shortname',
        ),
    ]
